### ISSUE TITLE
Wrong ordering of configured networks

### ISSUE THREAD

**Issue by lahwaacz** [loh-tar/wpa-cute#1]
On the "Networks" tab, networks are ordered by the ID like this: 0, 1, 10, 11, 12, ..., 2, 20, ..., 3, ...

Also the `id_str` could be visible as assigned in the config, but I'm not sure if wpa_supplicant passes it to frontends.

**Comment by loh-tar** [comment]
Thanks for your interest and reporting.

Unfortunately have I currently not the mood to dig into this issue. But I guess it is related to some old known problem, the lack of some additionally parameter how to sort some column in a QTreeWidget. Some solution seems to exist but I don't know if it really will work in this case because we need both, sorting alphabetic and numeric.

https://stackoverflow.com/a/366637

Some other solution would be to pad the number with zeros but I'm not sure if that looks nicer. 0001 0002 0010 0020

Regarding the id_str I have doubts how bad needed it is to have it always visible in that overview, but I may have missed something.

**Comment by lahwaacz** [comment]
As for the `id_str`: many public networks use quite cryptic SSIDs, but since the `id_str` is filled by the user, it can be assumed that it is a more readable description what the network is, where it is located etc.

**Comment by loh-tar** [comment]
I see. 
Would it be nice to replace the SSID by id_str when id_str is set? Perhaps with a hint like "ID:<YourString>"

However, after a quick look at the code, that all is not so simple. These network list is nothing else than "wpa_cli list_networks". So any more information to add need some effort.

**Comment by lahwaacz** [comment]
I was thinking about a separate column for `id_str`, but maybe it could be combined with the SSID column somehow...

I just noticed that when you click "Edit" for a network, the "Optional Settings" tab has an "IDString" entry, so the info is there - it's just about showing it directly in the list...

**Comment by loh-tar** [comment]
I have till now not used these id_str and an extra column would be always empty in my case. Thus these peculiar idea.

Sure is the info available, but need as said a little extra effort. 

It may take some weeks before I have the drive to fix the sorting but I will try it. Regarding the id_str would it be helpful to hear how bad my mixing idea is and how good these extra column...which I dislike.

**Comment by loh-tar** [comment]
After a recent look at that ID ordering issue I suggest to hide that column.

I can't find this ID nowhere else visible for the user and I think it has no benefit to show it in that network list.
On the other hand it is very important for intern use. So I don't like to hack on that in a quirky way by padding that number, not even with blanks. Who knows what then may stop working. 

So the only sane way would be these above linked operator change but I'm still not in the mood for that.

**Comment by lahwaacz** [comment]
Thanks for the fix!
